language: node_js
node_js:
    - 0.12.2
before_install:
    - npm cache clean
    - npm update npm -g
    - npm install -g bower grunt-cli codeclimate-test-reporter
install:
    - npm install --save-dev
    - bower install
script:
    - grunt
    - grunt dist
    - grunt jasmine:coverage
 after_script:
     - CODECLIMATE_REPO_TOKEN=b84eb3c970c5172f020363abf9797419fef0a959fbb2b8c130cbca06c3ef9686 codeclimate < coverage/lcov.info
